export type RealGoodsTypeSuggestion = {
  label: string;
  aliases?: string[];
};

export const REAL_GOODS_TYPE_SUGGESTIONS: RealGoodsTypeSuggestion[] = [
  { label: '缶バッチ', aliases: ['缶バッジ'] },
  { label: 'アクリルキーホルダー', aliases: ['アクキー'] },
  { label: 'アクリルパネル' },
  { label: 'ポスター' },
  { label: 'タペストリー' },
  { label: 'クリアファイル' },
  { label: '下敷き' },
  { label: 'ポストカード' },
  { label: 'ブロマイド' },
  { label: 'ステッカー' },
  { label: 'デカール' },
  { label: 'しおり' },
  { label: 'ノート' },
  { label: 'カレンダー' },
  { label: 'アクリルブロック' },
  { label: 'トートバッグ' },
  { label: 'ポーチ' },
  { label: '巾着' },
  { label: 'パーカー' },
  { label: 'マフラータオル' },
  { label: 'リストバンド' },
  { label: 'Tシャツ', aliases: ['ティーシャツ'] },
  { label: 'フルグラフィックTシャツ', aliases: ['フルグラフィックティーシャツ'] },
  { label: '帽子' },
  { label: '靴下' },
  { label: 'マスク' },
  { label: 'フィギュア' },
  { label: 'ねんどろいど' },
  { label: 'ぬいぐるみ' },
  { label: 'マスコットぬい' },
  { label: 'ぬいぐるみストラップ' },
  { label: 'ストラップ' },
  { label: 'マグカップ' },
  { label: 'グラス' },
  { label: 'タンブラー' },
  { label: 'クッション' },
  { label: '抱き枕' },
  { label: '箸' },
  { label: '食器' },
  { label: 'ランチョンマット' },
  { label: 'ラバーストラップ' },
  { label: 'メタルチャーム' },
  { label: '色紙' },
  { label: 'チェキ' },
  { label: 'CD', aliases: ['シーディー'] },
  { label: 'blue-ray', aliases: ['blu-ray', 'ブルーレイ'] },
  { label: 'ネットプリント' },
  { label: 'コースター' },
  { label: 'パスケース' },
  { label: 'ICカードステッカー', aliases: ['アイシーカードステッカー'] }
];
